services:
  redis:
    image: redis:alpine
    container_name: spring-board-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped


volumes:
  redis-data: