@baseUrl = http://localhost:8080

### 회원가입
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
  "username": "김민석",
  "email": "dgd5980@naver.com",
  "userId": "alstjr",
  "password": "que",
  "nickname": "민석"
}

### 로그인
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "userId" : "alstjr",
    "password" : "que"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
 %}


### 회원조회
GET {{baseUrl}}/api/users/alstjr
Authorization: Bearer {{accessToken}}


### 게시글 조회
GET {{baseUrl}}/api/boards
Authorization: Bearer {{accessToken}}

### 게시글 생성
POST {{baseUrl}}/api/boards
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "게시글 내용",
  "title": "게시글 제목",
  "postPassword": "1234"
}

### 게시글 수정
PUT {{baseUrl}}/api/boards/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "게시글 내용 수정" ,
  "postPassword": "1234"
}

### 게시글 삭제
DELETE {{baseUrl}}/api/boards/1
Authorization: Bearer {{accessToken}}


### 게시글 좋아요 누름
POST {{baseUrl}}/api/boards/5/like
Content-Type: application/json
Authorization: Bearer {{accessToken}}




